Add custom layout support to MAGI
raphael-group/magi pull request #33
Opened 2017-04-23 19:45 UTC by connorgr

Uses jQuery UI and vanilla CSS to provide new support for repositionable and resizable MAGI charts. Additionally, the visualizations are now responsive on window resize, which has been a bug since launch.

2017-04-26 12:31 UTC, mdml requested changes
## Overall
I tested by updating [MAGI](http://magi.brown.edu) to use this branch, since none of these changes affect the server-side app or database. Very nice work, and very useful!

@braphael8: please feel free to check out the live version to make sure I didn't miss any bugs or missing features.

## Questions
Is it easy to make the views vertically re-sizable? Seems like an obvious enhancement if not. Would also be very useful.

## Bugs
### Breaking
I did find some minor but breaking bugs, all related to the `VIEW_UTIL` functions. Can you fix?

### Non-breaking
I also found some non-breaking bugs:

1. The ability to hide the network and transcript views appears to be broken. Here's a screenshot where only the network SVG is hidden, rather than the whole panel body.
<img width="1111" alt="screen shot 2017-04-26 at 8 18 05 am" src="https://cloud.githubusercontent.com/assets/2043206/25434304/c959d37e-2a59-11e7-8f8c-3d60bb40da32.png">

2. The gradient legend for the network view is broken.
<img width="555" alt="screen shot 2017-04-26 at 8 19 58 am" src="https://cloud.githubusercontent.com/assets/2043206/25434321/d75168fc-2a59-11e7-9eb7-7348ca588d4b.png">

3. Not sure if this was already a problem, but the sort window is partially hidden.
<img width="1115" alt="screen shot 2017-04-26 at 8 17 48 am" src="https://cloud.githubusercontent.com/assets/2043206/25434359/08b03716-2a5a-11e7-849a-f189ae980aba.png">

2017-04-26 12:31 UTC, mdml commented on views/layout.jade
> +    link(rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css")
Why not in Bower?

2017-04-26 12:31 UTC, mdml commented on public/js/view.js
> +				{ type: 'text', text: 'Type: ' + mutationToName(d.ty) },
This is broken. Perhaps should be `VIEW_UTIL.mutationToName`?

2017-04-26 12:31 UTC, mdml commented on public/js/view.js
> +  pubmedLink: function(_id) {
References to this function are also broken.

2017-04-26 12:31 UTC, mdml commented on public/js/view.js
> +  cancerToName: function(c) {
References to this function are also broken.

2017-04-26 21:08 UTC, braphael8 commented
This looks great!  I didn't find any additional bugs beyond what Max reported above.

Being able to resize vertically would be extremely helpful; e.g. one might want to make the transcript view taller to show all mutations, rather than have to scroll.

2017-04-27 15:54 UTC, connorgr commented on views/layout.jade
> +    link(rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css")
fixed in b2c8466

2017-04-27 16:09 UTC, connorgr commented on public/js/view.js
> +  cancerToName: function(c) {
fixed in 53d7ab3

2017-04-27 16:09 UTC, connorgr commented on public/js/view.js
> +  pubmedLink: function(_id) {
fixed in 53d7ab3

2017-04-27 16:09 UTC, connorgr commented on public/js/view.js
> +				{ type: 'text', text: 'Type: ' + mutationToName(d.ty) },
fixed in 53d7ab3

2017-04-27 18:07 UTC, connorgr commented
@mdml 

Network color bug fixed in cd3f096

Aberration matrix sort bug fixed in f40b071

The resizing bug isn't necessarily a bug since it's expected behavior of the grid layout. For each row the elements will only vertically resize to the smallest element. The same thing happens for all the visualizations if you resize them to be half-width and then hide. One fix would be to just completely hide the panel body instead of resizing it using collapse, but that's a pretty big change to how the front end works right now.

I just took a stab at adding vertical resizing for the network and transcript charts, which is in a3094d8.

2017-08-22 17:15 UTC, mdml approved these changes

2017-08-22 17:16 UTC, merged